-- Disabled in favor of more light-weight wiki.vim.
-- Mostly, it's because it conflicted with vim-markdown and i wanted the better
-- code block syntax highlighting fro that plugin.
-- wiki.vim is also purely markdown-based, which solves my other big problem
-- with vimwiki.
--
--vim.cmd([[
--    let g:vimwiki_list = [{
--        \ 'path': '~/vimwiki/',
--        \ 'syntax': 'markdown',
--        \ 'ext': 'md',
--        \ 'links_space_char': '_'
--    \}]
--    let g:vimwiki_custom_wiki2html = 'vimwiki_markdown'
--    let g:vimwiki_global_ext = 0
--
--]])
--vim.keymap.set("n", "<localleader>wj", "<CMD>VimwikiMakeDiaryNote<CR>");
